using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Telnyx.NET.Enums;

namespace Telnyx.NET.Converters
{
    /// <summary>
    /// A custom JSON converter for the <see cref="GoogleLanguage"/> enum.
    /// This converter handles the serialization and deserialization of enum values to and from their string representations.
    /// </summary>
    public class GoogleLanguageConverter : JsonConverter<GoogleLanguage>
    {
        public override GoogleLanguage Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return value switch
            {
                "af" => GoogleLanguage.Afrikaans,
                "sq" => GoogleLanguage.Albanian,
                "am" => GoogleLanguage.Amharic,
                "ar" => GoogleLanguage.Arabic,
                "hy" => GoogleLanguage.Armenian,
                "az" => GoogleLanguage.Azerbaijani,
                "eu" => GoogleLanguage.Basque,
                "bn" => GoogleLanguage.Bengali,
                "bs" => GoogleLanguage.Bosnian,
                "bg" => GoogleLanguage.Bulgarian,
                "my" => GoogleLanguage.Burmese,
                "ca" => GoogleLanguage.Catalan,
                "yue" => GoogleLanguage.Cantonese,
                "zh" => GoogleLanguage.Chinese,
                "hr" => GoogleLanguage.Croatian,
                "cs" => GoogleLanguage.Czech,
                "da" => GoogleLanguage.Danish,
                "nl" => GoogleLanguage.Dutch,
                "en" => GoogleLanguage.English,
                "et" => GoogleLanguage.Estonian,
                "fil" => GoogleLanguage.Filipino,
                "fi" => GoogleLanguage.Finnish,
                "fr" => GoogleLanguage.French,
                "gl" => GoogleLanguage.Galician,
                "ka" => GoogleLanguage.Georgian,
                "de" => GoogleLanguage.German,
                "el" => GoogleLanguage.Greek,
                "gu" => GoogleLanguage.Gujarati,
                "iw" => GoogleLanguage.Hebrew,
                "hi" => GoogleLanguage.Hindi,
                "hu" => GoogleLanguage.Hungarian,
                "is" => GoogleLanguage.Icelandic,
                "id" => GoogleLanguage.Indonesian,
                "it" => GoogleLanguage.Italian,
                "ja" => GoogleLanguage.Japanese,
                "jv" => GoogleLanguage.Javanese,
                "kn" => GoogleLanguage.Kannada,
                "kk" => GoogleLanguage.Kazakh,
                "km" => GoogleLanguage.Khmer,
                "ko" => GoogleLanguage.Korean,
                "lo" => GoogleLanguage.Lao,
                "lv" => GoogleLanguage.Latvian,
                "lt" => GoogleLanguage.Lithuanian,
                "mk" => GoogleLanguage.Macedonian,
                "ms" => GoogleLanguage.Malay,
                "ml" => GoogleLanguage.Malayalam,
                "mr" => GoogleLanguage.Marathi,
                "mn" => GoogleLanguage.Mongolian,
                "ne" => GoogleLanguage.Nepali,
                "no" => GoogleLanguage.Norwegian,
                "fa" => GoogleLanguage.Persian,
                "pl" => GoogleLanguage.Polish,
                "pt" => GoogleLanguage.Portuguese,
                "pa" => GoogleLanguage.Punjabi,
                "ro" => GoogleLanguage.Romanian,
                "ru" => GoogleLanguage.Russian,
                "sr" => GoogleLanguage.Serbian,
                "si" => GoogleLanguage.Sinhala,
                "sk" => GoogleLanguage.Slovak,
                "sl" => GoogleLanguage.Slovenian,
                "es" => GoogleLanguage.Spanish,
                "su" => GoogleLanguage.Sundanese,
                "sw" => GoogleLanguage.Swahili,
                "sv" => GoogleLanguage.Swedish,
                "ta" => GoogleLanguage.Tamil,
                "te" => GoogleLanguage.Telugu,
                "th" => GoogleLanguage.Thai,
                "tr" => GoogleLanguage.Turkish,
                "uk" => GoogleLanguage.Ukrainian,
                "ur" => GoogleLanguage.Urdu,
                "uz" => GoogleLanguage.Uzbek,
                "vi" => GoogleLanguage.Vietnamese,
                "zu" => GoogleLanguage.Zulu,
                _ => throw new JsonException($"Value '{value}' is not supported for GoogleLanguage enum")
            };
        }

        public override void Write(Utf8JsonWriter writer, GoogleLanguage value, JsonSerializerOptions options)
        {
            var stringValue = value switch
            {
                GoogleLanguage.Afrikaans => "af",
                GoogleLanguage.Albanian => "sq",
                GoogleLanguage.Amharic => "am",
                GoogleLanguage.Arabic => "ar",
                GoogleLanguage.Armenian => "hy",
                GoogleLanguage.Azerbaijani => "az",
                GoogleLanguage.Basque => "eu",
                GoogleLanguage.Bengali => "bn",
                GoogleLanguage.Bosnian => "bs",
                GoogleLanguage.Bulgarian => "bg",
                GoogleLanguage.Burmese => "my",
                GoogleLanguage.Catalan => "ca",
                GoogleLanguage.Cantonese => "yue",
                GoogleLanguage.Chinese => "zh",
                GoogleLanguage.Croatian => "hr",
                GoogleLanguage.Czech => "cs",
                GoogleLanguage.Danish => "da",
                GoogleLanguage.Dutch => "nl",
                GoogleLanguage.English => "en",
                GoogleLanguage.Estonian => "et",
                GoogleLanguage.Filipino => "fil",
                GoogleLanguage.Finnish => "fi",
                GoogleLanguage.French => "fr",
                GoogleLanguage.Galician => "gl",
                GoogleLanguage.Georgian => "ka",
                GoogleLanguage.German => "de",
                GoogleLanguage.Greek => "el",
                GoogleLanguage.Gujarati => "gu",
                GoogleLanguage.Hebrew => "iw",
                GoogleLanguage.Hindi => "hi",
                GoogleLanguage.Hungarian => "hu",
                GoogleLanguage.Icelandic => "is",
                GoogleLanguage.Indonesian => "id",
                GoogleLanguage.Italian => "it",
                GoogleLanguage.Japanese => "ja",
                GoogleLanguage.Javanese => "jv",
                GoogleLanguage.Kannada => "kn",
                GoogleLanguage.Kazakh => "kk",
                GoogleLanguage.Khmer => "km",
                GoogleLanguage.Korean => "ko",
                GoogleLanguage.Lao => "lo",
                GoogleLanguage.Latvian => "lv",
                GoogleLanguage.Lithuanian => "lt",
                GoogleLanguage.Macedonian => "mk",
                GoogleLanguage.Malay => "ms",
                GoogleLanguage.Malayalam => "ml",
                GoogleLanguage.Marathi => "mr",
                GoogleLanguage.Mongolian => "mn",
                GoogleLanguage.Nepali => "ne",
                GoogleLanguage.Norwegian => "no",
                GoogleLanguage.Persian => "fa",
                GoogleLanguage.Polish => "pl",
                GoogleLanguage.Portuguese => "pt",
                GoogleLanguage.Punjabi => "pa",
                GoogleLanguage.Romanian => "ro",
                GoogleLanguage.Russian => "ru",
                GoogleLanguage.Serbian => "sr",
                GoogleLanguage.Sinhala => "si",
                GoogleLanguage.Slovak => "sk",
                GoogleLanguage.Slovenian => "sl",
                GoogleLanguage.Spanish => "es",
                GoogleLanguage.Sundanese => "su",
                GoogleLanguage.Swahili => "sw",
                GoogleLanguage.Swedish => "sv",
                GoogleLanguage.Tamil => "ta",
                GoogleLanguage.Telugu => "te",
                GoogleLanguage.Thai => "th",
                GoogleLanguage.Turkish => "tr",
                GoogleLanguage.Ukrainian => "uk",
                GoogleLanguage.Urdu => "ur",
                GoogleLanguage.Uzbek => "uz",
                GoogleLanguage.Vietnamese => "vi",
                GoogleLanguage.Zulu => "zu",
                _ => throw new JsonException($"Value '{value}' is not supported for GoogleLanguage enum")
            };

            writer.WriteStringValue(stringValue);
        }
    }

}
